---
deployment:
  tasks:
    - export DEPLOYPATH=/home/masahxco/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R img $DEPLOYPATH
    - /bin/cp -R portfolio $DEPLOYPATH
    - /bin/cp -R rogue $DEPLOYPATH
    - /bin/cp -R website $DEPLOYPATH
